Parameters:
  SecurityGroupDescription:
    Description: Descrição do Security group
    Type: String
  CidrIpDescription:
    Description: Descrição do IP para acesso SSH
    Type: String
Resources:
  #Instâncias EC2
  MyInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: sa-east-1a
      ImageId: ami-013702f40df1b9c78
      InstanceType: t2.micro
  
  # elastic IP
  MeuEIP:
    Type: "AWS::EC2::EIP"
    Properties:
      InstanceId: !Ref MyInstance

  # security Group
  ServerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref CidrIpDescription